#!/usr/bin/env bash

set -euo pipefail

dotnet build
dotnet test --filter FullyQualifiedName\~.Tests --collect:"XPlat Code Coverage"

dotnet publish --configuration Release --runtime linux-x64 --self-contained false Tsukiy0.Extensions.Templates.Default.Api 

dotnet swagger tofile --output Tsukiy0.Extensions.Templates.Default.Api/bin/Debug/net6.0/swagger.json Tsukiy0.Extensions.Templates.Default.Api/bin/Debug/net6.0/Tsukiy0.Extensions.Templates.Default.Api.dll v1