#!/usr/bin/env bash

set -euo pipefail

dotnet build
dotnet test Tsukiy0.Extensions.Core.Tests
dotnet test Tsukiy0.Extensions.AspNetCore.Tests
dotnet test Tsukiy0.Extensions.Logging.NLog.Tests
dotnet pack
