#!/usr/bin/env bash

set -euo pipefail

dotnet tool restore
dotnet reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:JsonSummary
cat coveragereport/Summary.json
