#!/usr/bin/env bash

set -euo pipefail

VERSION=$(jq -r ".version" package.json)
SOURCE=https://api.nuget.org/v3/index.json

dotnet nuget push Tsukiy0.Extensions.Core/bin/Debug/*.nupkg --api-key ${NUGET_API_KEY} --source ${SOURCE}
dotnet nuget push Tsukiy0.Extensions.AspNetCore/bin/Debug/*.nupkg --api-key ${NUGET_API_KEY} --source ${SOURCE}
dotnet nuget push Tsukiy0.Extensions.Logging.Core/bin/Debug/*.nupkg --api-key ${NUGET_API_KEY} --source ${SOURCE}
dotnet nuget push Tsukiy0.Extensions.Logging.NLog/bin/Debug/*.nupkg --api-key ${NUGET_API_KEY} --source ${SOURCE}
dotnet nuget push Tsukiy0.Extensions.Logging.AspNetCore/bin/Debug/*.nupkg --api-key ${NUGET_API_KEY} --source ${SOURCE}
