#!/usr/bin/env bash

set -euxo pipefail

dotnet tool restore

dotnet outdated

dotnet reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:TextSummary
cat coveragereport/Summary.txt
