#!/usr/bin/env bash

set -euxo pipefail

dotnet test Tsukiy0.Extensions.Data.Aws.IntegrationTests --collect:"XPlat Code Coverage"
dotnet test Tsukiy0.Extensions.Messaging.Aws.IntegrationTests --collect:"XPlat Code Coverage"
