#!/usr/bin/env bash

set -euo pipefail

VERSION=$(jq -r ".version" package.json)
NUGET_PKG_DIR=/tmp/nuget
SOURCE=https://api.nuget.org/v3/index.json

pack() {
    dotnet pack ${1} --include-symbols -o ${NUGET_PKG_DIR}
}

pack Tsukiy0.Extensions.AspNetCore
pack Tsukiy0.Extensions.Configuration
pack Tsukiy0.Extensions.Configuration.Aws
pack Tsukiy0.Extensions.Core
pack Tsukiy0.Extensions.Correlation
pack Tsukiy0.Extensions.Data
pack Tsukiy0.Extensions.Data.Aws
pack Tsukiy0.Extensions.DependencyInjection
pack Tsukiy0.Extensions.Http
pack Tsukiy0.Extensions.Json
pack Tsukiy0.Extensions.Logging
pack Tsukiy0.Extensions.Logging.NLog
pack Tsukiy0.Extensions.Processor
pack Tsukiy0.Extensions.Processor.Aws
pack Tsukiy0.Extensions.Testing

dotnet nuget push "${NUGET_PKG_DIR}/*.nupkg" --source ${SOURCE} --api-key ${NUGET_API_KEY} --skip-duplicate
